// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://ihwpwunlrgovyzvxejzl.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod3B3dW5scmdvdnl6dnhlanpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTgzNDksImV4cCI6MjA2NTI5NDM0OX0.c9q192OK6Jbkij-c8k9TuSJkbLnCgyDucyg5oKQqynI";

//new keys


const SUPABASE_URL="https://iwvhpyjqndabydsteije.supabase.co"
const SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dmhweWpxbmRhYnlkc3RlaWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDc2ODUsImV4cCI6MjA2NTcyMzY4NX0.DDn6K0Dg-wlBaimiQFXI4gQOHXz6t7suEL8YShKwqfE"
        

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
